### PR TITLE
Supports `--ckpt-dir` and `--vae-dir`

### PR DESCRIPTION
**Pull request by ddPn08**
As the title says.

### CODE REVIEW

**Comment by ddPn08** [comment]
It was more complicated than I expected. This is still not perfect.

**Comment by ddPn08** [comment]
It worked fine.

**Comment by arenasys** [comment]
it will show full paths in the dropdown even if there are no duplicates

**Comment by ddPn08** [comment]
I believe it was fixed in this commit.

**Comment by arenasys** [comment]
even with `--ckpt-dir` the webui will load models in `models/Stable-diffusion`. my loading code was inflexible to begin with, i will rewrite it.

**Comment by arenasys** [comment]
added support for this in 16128c8c5c4415a2746b601843d179302e5ac220

**Comment by ddPn08** [comment]
Thank you very much.

**Pull request closed without merging**
